### ISSUE TITLE
Question about <ApolloProvider client={ client }>

### ISSUE THREAD

**Issue by yudyananda** [imranhsayed/woo-next#39]
Hi @imranhsayed can you elaborate about `<ApolloProvider client={ client }>`? i know `client` is referring to `ApolloClient.js` but If I'm not mistaken the the page component like index and product still using import client.   So which component use it?

**Comment by imranhsayed** [comment]
@yudyananda `client` must to be passed to the ApolloProvider as a apollo requirement, so that you can make graphql queries and mutation within the component. If you observe the components like AddToCartButton are make the GraphQL queries and mutations. Try removing it and you will get this error
![image](https://user-images.githubusercontent.com/11497423/90016916-5d977b80-dcc8-11ea-8a54-30526cf0d331.png)

Pages need it components use useQuery  and useMutation, while pages use client.query. We will soon be updating it to the latest version of Apollo. 
You can read more about it here 
https://www.apollographql.com/docs/react/get-started/

**Comment by tedc** [comment]
Hi  @imranhsayed , 
I'm trying to create a search/filter tool based on query url parameters (ie: ?category=slug) for products archive page using the search model you used in nextjs-headless-wordpress (https://github.com/imranhsayed/nextjs-headless-wordpress/blob/main/frontend/pages/search.js), but when useLazyQuery starts to work, I get the error in the screenshot above (Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options).
Do you have any idea about it? What can I do to avoid it?
